Dev -> Main (#22)
* dark mode integrate done

* signup issue fixed

* lint check

* lint check agin

* fix

* fix

* chore: integrate husky commit message

* chore: min fix

* feat: env functionality

* feat: add Next.js i18n internationalization/localization (#10)

* feat: add Next.js i18n internationalization/localization

* feat: standardize locales and localize navbar/search

* feat: improve navbar UI and mobile LanguageSwitcher

* chore: min fix

* docs: add comprehensive project documentation (#12)

* docs: add comprehensive project documentation

* Update DOCUMENTATION.md

---------

Co-authored-by: Muhammad Hassam Yahya <hassam@unstucklabs.com>

* refactor: remove unnecessary [lang] layout (#13)

* Feat/jest integration (#14)

* feat: jest integration with Login Page unit test

* chore: prettier done

* Test/add homepage component tests (#16)

* test: add signup component test suite

* test: add HomePage component test suite

* test: add LanguageSwitcher component test suite

* test: add comprehensive test coverage for remaining

* feat: supabase business logic tests cases done (#19)

* Upgrate next js (#20)

* feat: next js version update

* chore: lint fixes

* chore: some tests fixes

---------

Co-authored-by: alishah009 <ali.shah@unstucklabs.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,14 @@
-#!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
+#!/usr/bin/env sh
+. "$(dirname -- "$0")/_/husky.sh"
 
-yarn lint:fix
+# Check for empty files
+echo "🔍 Checking for empty files..."
+if git diff --cached --name-only | xargs -I{} sh -c "[ -f {} ] && [ ! -s {} ]" | grep .; then
+  echo "Error: Empty files detected in commit. Please remove them."
+  exit 1
+fi
+
+yarn validate
+yarn test
 yarn prettier --write .
+# empty files , tests
